UIQM-72: Change delete row behavior
folio-org/ui-quick-marc pull request #116
Opened 2021-02-01 11:54 UTC by Yuliia-Dovhal

### UIQM-72: Edit quickMARC bibliographic record: Change delete row behavior

## Purpose
Change delete row behavior - remove deleting modal on each delete action, but show confirmation modal after clicking `Save and close` button.

## Pre-Merge Checklist
Before merging this PR, please go through the following list and take appropriate actions.
- [x] I've added appropriate record to the CHANGELOG.md
- Does this PR meet or exceed the expected quality standards?
  - [ ] Code coverage on new code is 80% or greater
  - [ ] Duplications on new code is 3% or less
  - [ ] There are no major code smells or security issues
- Does this introduce breaking changes?
  - [ ] If any API-related changes - okapi interfaces and permissions are reviewed/changed correspondingly
  - [ ] There are no breaking changes in this PR.

If there are breaking changes, please **STOP** and consider the following:

- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
  - [ ] If not, please create them
  - [ ] Do they contain the appropriate level of detail?  Which endpoints/schemas changed, etc.
  - [ ] Do they have all they appropriate links to blocked/related issues?
- Are the JIRAs under active development?
  - [ ] If not, contact the project's PO and make sure they're aware of the urgency.
- Do PRs exist for these changes?
  - [ ] If so, have they been approved?

Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.

While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR assignee.

2021-02-01 13:24 UTC, Vladyslav-Velytskyi commented on src/QuickMarcEditor/QuickMarcEditorRows/QuickMarcEditorRows.js
> +                  maxLength={3}
No any numbers from the ceiling. Please make a constant for it.

2021-02-02 16:05 UTC, BogdanDenis requested changes

2021-02-04 10:09 UTC, BogdanDenis approved these changes

2021-02-04 12:15 UTC, Vladyslav-Velytskyi approved these changes

2021-02-04 13:36 UTC, uladislausamets commented on src/QuickMarcEditor/QuickMarcEditorRows/BytesField/BytesField.js
> +  const getMaxLengthByType = () => (config.type === SUBFIELD_TYPES.BYTE ? FIXED_FIELD_MAX_LENGTH : undefined);
```suggestion
  const getMaxLengthByType = config.type === SUBFIELD_TYPES.BYTE ? FIXED_FIELD_MAX_LENGTH : undefined;
```

2021-02-04 13:37 UTC, uladislausamets approved these changes

2021-02-04 14:16 UTC, merged