UIQM-190: Edit MARC holdings (quickMARC) update paneheader display
folio-org/ui-quick-marc pull request #265
Opened 2022-01-24 14:39 UTC by Svitlana-Korol

## Description
Edit MARC holdings (quickMARC) update paneheader display

## Issues
[UIQM-190] (https://issues.folio.org/browse/UIQM-190)

## Video

https://user-images.githubusercontent.com/96055497/150803177-b20dd5af-e5ed-4a5a-8134-0732500c38fc.mp4

![image](https://user-images.githubusercontent.com/96055497/150986293-8abcc7c7-5c26-44a2-855a-68c17e9a9020.png)

2022-01-25 08:43 UTC, BogdanDenis approved these changes

2022-01-26 13:03 UTC, BogdanDenis approved these changes

2022-01-26 13:14 UTC, mariiaschv requested changes

2022-01-26 13:14 UTC, mariiaschv commented on src/QuickMarcEditor/QuickMarcEditor.test.js
> +  describe('when marc record is of type HOLDINGS', () => {
There is a test suite `when marc record is of type HOLDINGS` already, it is a bit higher. It's better to move your test case there.

2022-01-26 14:59 UTC, mariiaschv approved these changes

2022-01-26 15:23 UTC, merged