UI qm 243
folio-org/ui-quick-marc pull request #322
Opened 2022-06-05 23:37 UTC by ODanyor

## Purpose
Optimistic Locking: Do not send update request when user attempts to update older version of MARC bib/holdings/authority

## Approach
Request to fetch the latest _instancePromise_ is made. Then we compare fetched _instancePromise_'s version with current _instancePromise_'s version. If it is different, the conflict detection banner is showed up with error message.

2022-06-06 08:01 UTC, BogdanDenis requested changes

2022-06-06 08:01 UTC, BogdanDenis commented on src/QuickMarcEditor/QuickMarcEditWrapper.test.js
> +        expect(mutator.quickMarcEditInstance.GET).toHaveBeenCalled();
Please also add a test, where `quickMarcEditInstance` returns a different record version, so we can verify that optimistic locking banner is shown

2022-06-06 09:41 UTC, mariiaschv approved these changes

2022-06-07 15:01 UTC, BogdanDenis approved these changes

2022-06-08 09:59 UTC, merged