UIQM-256: Change field level actions display
folio-org/ui-quick-marc pull request #352
Opened 2022-08-22 12:23 UTC by odoniyor

## Purpose
Change field level actions display

## Approach
Changed items order of `QuickMarcEditorRows`. Removed a fixed width from `quickMarcEditorActions` styles which was causing an extra space between `quickMarcEditorActions` items and `quickMarcEditorRowContent` item.

## Screenshots
![actions-display](https://user-images.githubusercontent.com/111242500/185919005-aafd93d2-efbf-4e7e-9662-c73b078d349e.jpg)

## Issues
[UIQM-256](https://issues.folio.org/browse/UIQM-256)

2022-08-23 08:17 UTC, BogdanDenis approved these changes

2022-08-24 12:57 UTC, NikitaSedyx approved these changes

2022-08-25 12:00 UTC, Dmytro-Melnyshyn commented
Also needed to move protection icon.
After clicking on the trash button the focus should be on the trash button of the next row.
Нover functionality needs to be changed for action icons.

2022-08-29 10:32 UTC, BogdanDenis requested changes
Hey Doniyor, there are still several issues:

1. Hovering over action icons doesn't use `<Tooltip>` component https://folio-org.github.io/stripes-components/?path=/story/components-tooltip--basic-usage
2. There's a lot of space between move icons and other icons, around link button and protected field icon. We should make spacing more consistent
![image](https://user-images.githubusercontent.com/19309423/187181657-8486aeac-c556-45bd-acf9-8418774415f4.png)
![image](https://user-images.githubusercontent.com/19309423/187181732-a2f1fc9e-883e-42c7-892a-820b2513443c.png)
3. When you delete field before `999` - focus is not on `999`'s move up icon

2022-09-01 11:22 UTC, BogdanDenis approved these changes

2022-09-01 11:34 UTC, Dmytro-Melnyshyn approved these changes

2022-09-01 13:15 UTC, merged