UIQM-337: Controlled subfield is displayed as not controlled after linking of MARC Bib field with MARC Authority
folio-org/ui-quick-marc pull request #442
Opened 2023-01-19 17:12 UTC by Dmytro-Melnyshyn

## Purpose
Subfields that are in the linking rules but not in the authority should be removed.

## Issue
[UIQM-337](https://issues.folio.org/browse/UIQM-337)

## Screencast

https://user-images.githubusercontent.com/77053927/213513370-26ad4d09-dc14-442e-8306-96c009cbda97.mp4

## Approach

#### TODOS and Open Questions

## Learning

## Pre-Merge Checklist
Before merging this PR, please go through the following list and take appropriate actions.
- [ ] I've added appropriate record to the CHANGELOG.md
- Does this PR meet or exceed the expected quality standards?
  - [ ] Code coverage on new code is 80% or greater
  - [ ] Duplications on new code is 3% or less
  - [ ] There are no major code smells or security issues
- Does this introduce breaking changes?
  - [ ] If any API-related changes - okapi interfaces and permissions are reviewed/changed correspondingly
  - [ ] There are no breaking changes in this PR.

If there are breaking changes, please **STOP** and consider the following:

- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
  - [ ] If not, please create them
  - [ ] Do they contain the appropriate level of detail?  Which endpoints/schemas changed, etc.
  - [ ] Do they have all they appropriate links to blocked/related issues?
- Are the JIRAs under active development?
  - [ ] If not, contact the project's PO and make sure they're aware of the urgency.
- Do PRs exist for these changes?
  - [ ] If so, have they been approved?

Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.

While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR assignee.

2023-01-20 11:16 UTC, BogdanDenis requested changes

2023-01-20 11:16 UTC, BogdanDenis commented on src/hooks/useAuthorityLinking/useAuthorityLinking.js
> +  const removeSubfieldsIfThereAreNotInAuthority = useCallback((bibSubfields, authField, bibTag) => {
We already have a function that iterates over authority subfields, I think it'll be shorter to add an `else` statement inside `copySubfieldsFromAuthority` here - https://github.com/folio-org/ui-quick-marc/blob/master/src/hooks/useAuthorityLinking/useAuthorityLinking.js#L48
```
else {
  delete bibSubfields[formatSubfieldCode(subfieldCode)];
}
```

2023-01-23 08:01 UTC, ZazaManagadze approved these changes

2023-01-23 09:21 UTC, BogdanDenis approved these changes

2023-01-23 11:15 UTC, merged