UIQM-501: Actualize new linked fields on save.
folio-org/ui-quick-marc pull request #562
Opened 2023-07-12 14:49 UTC by Dmytro-Melnyshyn

## Purpose
Actualize new linked fields on save.

## Issue
[UIQM-501](https://issues.folio.org/browse/UIQM-501)

## Screencast

https://github.com/folio-org/ui-quick-marc/assets/77053927/d8d1fceb-673c-4912-9527-f73325cd5809

## Approach

#### TODOS and Open Questions

## Learning

## Pre-Merge Checklist
Before merging this PR, please go through the following list and take appropriate actions.
- [ ] I've added appropriate record to the CHANGELOG.md
- Does this PR meet or exceed the expected quality standards?
  - [ ] Code coverage on new code is 80% or greater
  - [ ] Duplications on new code is 3% or less
  - [ ] There are no major code smells or security issues
- Does this introduce breaking changes?
  - [ ] If any API-related changes - okapi interfaces and permissions are reviewed/changed correspondingly
  - [ ] There are no breaking changes in this PR.

If there are breaking changes, please **STOP** and consider the following:

- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
  - [ ] If not, please create them
  - [ ] Do they contain the appropriate level of detail?  Which endpoints/schemas changed, etc.
  - [ ] Do they have all they appropriate links to blocked/related issues?
- Are the JIRAs under active development?
  - [ ] If not, contact the project's PO and make sure they're aware of the urgency.
- Do PRs exist for these changes?
  - [ ] If so, have they been approved?

Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.

While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR assignee.

2023-07-13 11:02 UTC, mariia-aloshyna commented on src/hooks/useAuthorityLinking/useAuthorityLinking.js
> +      ...pick(groupSubfields(field, controlledSubfields), 'uncontrolledAlpha', 'uncontrolledNumber'),
Move 'uncontrolledAlpha' and 'uncontrolledNumber' to constants, please

2023-07-13 11:56 UTC, BogdanDenis requested changes

2023-07-13 11:56 UTC, BogdanDenis commented on src/hooks/useAuthorityLinking/useAuthorityLinking.js
> +    const isNewLinkedField = (field) => field.linkDetails?.status === AUTOLINKING_STATUSES.NEW;
We need to update all links, not just new ones to make sure all links are in sync with authority records

2023-07-13 11:56 UTC, BogdanDenis commented on src/hooks/useAuthorityLinking/useAuthorityLinking.js
> +        const suggestedField = suggestedFields[suggestedFieldIndex];
you can use `suggestedFields.shift()` to get the first value - I think it will look cleaner without indexes and increments

2023-07-13 11:56 UTC, BogdanDenis commented on src/hooks/useAuthorityLinking/useAuthorityLinking.js
> +      if (isNewLinkedField(field)) {
Let's use fail-fast approach: check for negative cases that don't need special treatment first:
```js
if (!someCondition) {
  return field;
}

// do some more actions here
```

It's going to reduce code complexity by making it less indented

2023-07-13 11:56 UTC, BogdanDenis commented on src/hooks/useAuthorityLinking/useAuthorityLinking.js
> +        if (suggestedField.linkDetails && suggestedField.linkDetails.status !== AUTOLINKING_STATUSES.ERROR) {
Probably can we written as 
```js
if (suggestedField.linkDetails?.status !== AUTOLINKING_STATUSES.ERROR)
```

2023-07-13 11:56 UTC, BogdanDenis commented on src/QuickMarcEditor/QuickMarcEditWrapper.js
> +        formValuesWithActualizedNewLinkedFields,
We also need to actualize links when Deriving and Creating bib records

2023-07-13 11:56 UTC, BogdanDenis commented on src/QuickMarcEditor/QuickMarcEditWrapper.test.js
> +        const formValuesToProcess = flow(
This test is tied too much to implementation. It's better to define two constants (initial values and expected values), mock click on save and make sure actualize links was called with expected values

2023-07-14 10:36 UTC, BogdanDenis approved these changes

2023-07-17 08:34 UTC, Dmytro-Melnyshyn commented
@mariia-aloshyna please take a look at this [pull request](https://github.com/folio-org/ui-quick-marc/pull/562) again, I added `uncontrolledAlpha` and `uncontrolledNumber` to constants.

2023-07-17 17:10 UTC, merged