UIQM-681 Re-enable some FE validation rules
folio-org/ui-quick-marc pull request #710
Opened 2024-08-09 11:15 UTC by BogdanDenis

## Description
Re-enable some FE validation rules. Some of them will not be implemented on BE side so we still need to have a few rules on FE side
Update LCCN duplication validation to be a rule instead of a separate hook

## Screenshots

## Issues
[UIQM-681](https://folio-org.atlassian.net/browse/UIQM-681)

2024-08-12 11:41 UTC, Dmytro-Melnyshyn requested changes

2024-08-12 11:41 UTC, Dmytro-Melnyshyn commented on src/hooks/useValidation/validators.test.js
> +import { waitFor } from '@folio/jest-config-stripes/testing-library/react';
eslint warning

2024-08-12 13:48 UTC, Dmytro-Melnyshyn approved these changes

2024-08-13 06:22 UTC, artem-blazhko approved these changes

2024-08-13 08:06 UTC, merged